### ISSUE TITLE
missing build / install instructions

### ISSUE THREAD

**Issue by noerw** [LuxoftLab/ShareClipboard#43]
Would it be possible to include instructions on how to build this?
I didn't even find a makefile or something similar.
I'd like to check this tool out :^)

greets

**Comment by Asalle** [comment]
Hi Norwin,

thank you for your interest in SharedClipboard!
You are our first official user :dancer: 

In general, you should install Qt 5 and run qmake and make in terminal (I will write a wiki page with more details later). If you don't like terminals, you can install Qt Creator and simply press F5 or "Run".

There is a certain peculiarity in this project: there are as many as 3 versions of it, all of them equally under heavy development right now. The versions 1, 2, 3 can be found under branches "v1", "v2" and "master" respectively.

v1: Is lightweight and primitive and, in general, is not lead by me, but it can transfer text (no images or files) between PC and Android.

v2 : is more heavy and does not support Android, but you can send and receive files and images.

v3 : is not working so far.

As you are the only user so far, you can tell me your OS and processor architecture and I will try to build it for you personally.

Have a nice day!

**Comment by noerw** [comment]
lol thats great! :+1: 
I'm on Ubuntu 15.10 x64. My other machine runs win7 x64.
I'm gonna try to build this later, at least on linux :)

**Comment by Asalle** [comment]
Hi again Norwin,
I released the v0.1 of SharedClipboard in the 'releases' section of the repository.
upd: and also the v0.2
We are glad to hear both positive and negative reviews!
Enjoy!

**Comment by noerw** [comment]
Thanks for putting that together :) I'm having issues though:
- Can't download v0.2, github/amazonaws returns an error "key not found" somehow.
- On Ubuntu Gnome 15.10 amd64 with `libglu1-dev v9.0.0-2` i have the following error when launching the executable of v0.1:
  
  ```
  $: chmod +x ./SharedClipboard-0.1
  $: ./SharedClipboard-0.1
  symbol lookup error: ./SharedClipboard-0.1: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject
  ```

Edit:
- The error seems to refer to
  
  ```
  QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*)
  ```
  
  (http://demangler.com/)
- i have `libqt 5.4.2` as well as `libqt4 v4.8.6` installed.

**Comment by Asalle** [comment]
Hi Norwin,
I wrote a small [wiki-page](https://github.com/LuxoftLab/ShareClipboard/wiki/How-to-build-SharedClipboard-%28linux%29) about SC installation, check it out. I guess, that passing the executable is yet not an option.

If something goes wrong or you have any additions to the wiki page -- please, tell me.

Best regards!

**Comment by noerw** [comment]
Thanks! With Qt 5.5 and Qt creator it built fine on Ubuntu.
On windows i'm still having issues though, I guess my Qt creator installation is messed up..
Thus I'm unable to test the actual functionality yet for my usecase.
I'll retry in the next days & let you know

Greets, N

**Comment by Asalle** [comment]
I consider this issue closed then. If you succeed with installation of Qt on Windows, please let me know if SC works okay in your usecase.
Best regards!
